esphome:
  name: internal-garagedoor

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Habilitar logs por puerto serie y red (muy útil para depurar)
logger:

# Permite cargar firmware OTA después de la primera vez
api:
ota:
  platform: esphome

# Ejemplo básico: un switch que controla un pin GPIO
switch:
  - platform: gpio
    id: internal_door_click
    name: "Internal Garage Door Button"
    pin: 2
    inverted: true

cover:
  - platform: time_based
    id: internal_garage_door
    device_class: garage
    name: Internal garage door
    open_action:
      - switch.turn_on: internal_door_click
      - delay: 3s
      - switch.turn_off: internal_door_click
    open_duration: 30s

    close_action:
      - switch.turn_on: internal_door_click
      - delay: 3s
      - switch.turn_off: internal_door_click
    close_duration: 30s

    stop_action:
      - switch.turn_off: internal_door_click
